server:
  port: 8086

spring:
  datasource:
    url: 'jdbc:h2:file:C:\YMZ\Udemy\Todo-App\todo.db'
  h2.console:
    enabled: true
    path: '/h2-console'
  banner:
    location: 'file:banner.txt'
  main:
    banner-mode: off

task:
  template:
    allow-multiple-tasks: true