server:
  port: 8086

spring:
  h2.console:
    enabled: true
    path: '/h2-console'
  datasource:
    url: 'jdbc:h2:file:C:\YMZ\Udemy\Todo-App\todo.db'
  banner:
    location: 'file:banner.txt'

my.prop: 'test'